name: 'Build and Publish to Cloudflare Pages'

on:
  push:
    branches: ['master']

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Directory Tree
        # working-directory: ./
        run: tree

      # Run a build step
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: yarn
      - name: Building the App
        run: yarn build

      # Cloudflare Step
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: cl346oaAearTwH0JTRPMGj3v22DCZnF6bWU5g86G
          accountId: 87dd9ca44f4ea8ed5e8cce8d913b29d2
          projectName: petakon-dev
          directory: .svelte-kit/cloudflare
          branch: main
          wranglerVersion: '3'
